### ISSUE TITLE
Issues with v3.0.0 and azuread.Application

### ISSUE THREAD

**Issue by chr15murray** [pulumi/pulumi-azuread#130]
I'm just starting a new project so pulled in the latest version which happened to be v3.0.0

Creating a new azuread app works under 2.6.1 as simply.
`const test = new azuread.Application("test", undefined);`

But under 3.0.0 this now results in an error: TypeError: pulumi.runtime.registerResourceModule is not a function

```
pulumi preview --debug
Previewing update (prod):
debug: AzureRM Client User Agent: HashiCorp Terraform/0.11+compatible (+https://www.terraform.io) Terraform Plugin SDK/1.10.0 terraform-provider-azuredevops/dev
debug: 2020/12/08 19:15:33 getAzdoClient(): Created core, build, operations, and serviceendpoint clients successfully!
debug: Registering resource: t=pulumi:pulumi:Stack, name=azure-devops-prod, custom=false, remote=false
debug: RegisterResource RPC prepared: t=pulumi:pulumi:Stack, name=azure-devops-prod
  pulumi:pulumi:Stack: (same)
    [urn=urn:pulumi:prod::azure-devops::pulumi:pulumi:Stack::azure-devops-prod]
debug: RegisterResource RPC finished: resource:azure-devops-prod[pulumi:pulumi:Stack]; err: null, resp: urn:pulumi:prod::azure-devops::pulumi:pulumi:Stack::azure-devops-prod,,,,
debug: Running program '/Users/chrismurray/git/Infrastructure/pulumi/azure-devops' in pwd '/Users/chrismurray/git/Infrastructure/pulumi/azure-devops' w/ args:
debug: RegisterResourceOutputs RPC prepared: urn=urn:pulumi:prod::azure-devops::pulumi:pulumi:Stack::azure-devops-prod
error: Running program '/Users/chrismurray/git/Infrastructure/pulumi/azure-devops' failed with an unhandled exception:
TypeError: pulumi.runtime.registerResourceModule is not a function
    at Object.<anonymous> (/Users/chrismurray/git/Infrastructure/pulumi/azure-devops/node_modules/@pulumi/index.ts:82:16)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1131:10)
    at Module.load (node:internal/modules/cjs/loader:967:32)
    at Function.Module._load (node:internal/modules/cjs/loader:807:14)
    at Module.require (node:internal/modules/cjs/loader:991:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/Users/chrismurray/git/Infrastructure/pulumi/azure-devops/index.ts:3:1)
    at Module._compile (node:internal/modules/cjs/loader:1102:14)
    at Module.m._compile (/Users/chrismurray/git/Infrastructure/pulumi/azure-devops/node_modules/ts-node/src/index.ts:439:23)
debug: RegisterResourceOutputs RPC finished: urn=urn:pulumi:prod::azure-devops::pulumi:pulumi:Stack::azure-devops-prod; err: null, resp:
```

Reverting to v2.6.1 resolves the issue.

**Comment by leezen** [comment]
Do you mind sharing what version of the CLI and the version of `@pulumi/pulumi` you're pulling in?

**Comment by mikhailshilkov** [comment]
This error message looks like something fundamental was broken in that environment. Since it's been almost three years since than, we don't have a repro or any additional comments from others, I'll go ahead and close this issue as stale
